server:
  port: 8081  # The Order Service will run on this port

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    # This URL connects to your 'postgres-order' container on port 5433
    url: jdbc:postgresql://localhost:5433/order_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update # IMPORTANT: This creates the tables for you automatically!
    show-sql: true     # This lets you see the SQL commands in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect